version: '3.8'

services:
  web:
    build: .
    container_name: qingzhu_english
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-change-this-in-production
      - DATABASE_URL=sqlite:///data/qingzhu_english.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加数据库服务（如果需要使用PostgreSQL）
  # db:
  #   image: postgres:13
  #   container_name: qingzhu_db
  #   environment:
  #     POSTGRES_DB: qingzhu_english
  #     POSTGRES_USER: qingzhu
  #     POSTGRES_PASSWORD: your-db-password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

  # 可选：添加Redis服务（用于缓存和会话存储）
  # redis:
  #   image: redis:6-alpine
  #   container_name: qingzhu_redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

volumes:
  # postgres_data:
  # redis_data:
  logs:
  data:

networks:
  default:
    name: qingzhu_network